package de.heinerkuecker.coroutine;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;

import de.heinerkuecker.coroutine.proc.arg.Argument;
import de.heinerkuecker.coroutine.proc.arg.Parameter;
import de.heinerkuecker.util.ArrayDeepToString;

/**
 * Argument values {@link Map}
 * for {@link Parameter}
 * with type check at runtime.
 *
 * Parameters are unmodifiable.
 *
 * @author Heiner K&uuml;cker
 */
public class Arguments
implements Iterable<Entry<String, Object>>
{
    private final HashMap<String, Object> values = new HashMap<>();

    /**
     * Constructor.
     *
     * @param params
     * @param args
     * @param parent
     */
    public Arguments(
            final Map<String, Parameter> params ,
            final Argument<?>[] args ,
            final CoroIteratorOrProcedure<?> parent )
    {
        final Set<String> missedMandantoryParamNames = new HashSet<>();

        if ( params != null )
        {
            for ( Parameter param : params.values() )
            {
                if ( param.isMandantory )
                {
                    missedMandantoryParamNames.add(
                            param.name );
                }
            }
        }

        if ( args != null )
        {
            for ( final Argument<?> argument : args )
            {
                if ( ! params.containsKey( argument.name ) )
                {
                    throw new IllegalArgumentException(
                            "undefined argument name: " +
                            argument.name );
                }

                missedMandantoryParamNames.remove( argument.name );

                final Object argumentValue =
                        argument.expression.evaluate(
                                parent );

                if ( argumentValue != null )
                {
                    final Parameter param =
                            params.get(
                                    argument.name );

                    if ( ! param.type.isInstance( argumentValue ) )
                    {
                        throw new WrongArgumentClassException(
                                argument.name ,
                                //expectedClass
                                param.type ,
                                //wrongValue
                                argumentValue );
                    }

                    values.put(
                            argument.name ,
                            argumentValue );
                }
            }
        }

        if ( ! missedMandantoryParamNames.isEmpty() )
        {
            throw new MissedArgumentException(
                    missedMandantoryParamNames.toString() );
        }
    }

    public static Arguments EMPTY =
            new Arguments(
                    //params
                    null ,
                    //args
                    null ,
                    //parent
                    null );

    /**
     * Get argument value.
     *
     * @param argumentName
     * @return argument value
     */
    public Object get(
            final String argumentName )
    {
        // TODO throw exception, when variableName is unknown
        return this.values.get(
                Objects.requireNonNull(
                        argumentName ) );
    }

    /**
     * @see Object#toString()
     */
    @Override
    public String toString()
    {
        //return "Variables [innerVars=" + this.innerVars + "]";
        //return String.valueOf( this.values );

        StringBuilder sb = new StringBuilder();
        for ( final Entry<String, Object> valuesEntry : this.values.entrySet() )
        {
            String key = valuesEntry.getKey();
            Object value = valuesEntry.getValue();

            if ( sb.length() != 0 )
            {
                sb.append(',').append(' ');
            }

            sb.append( key );
            sb.append('=');
            sb.append(
                    value == this.values
                        ? "(this Map circular reference)"
                        : ArrayDeepToString.deepToString( value ) );
        }
        return "" + '{' + sb + '}';
    }

    /**
     * @see java.lang.Iterable#iterator()
     */
    @Override
    public Iterator<Entry<String, Object>> iterator()
    {
        return this.values.entrySet().iterator();
    }

    /**
     * Exception
     */
    public static class WrongArgumentClassException
    extends RuntimeException
    {
        /**
         * Generated by Eclipse.
         */
        private static final long serialVersionUID = -3843489649279228520L;

        /**
         * Constructor.
         *
         * @param message
         */
        public WrongArgumentClassException(
                final String argumentName ,
                final Class<?> expectedClass ,
                final Object wrongValue )
        {
            super(
                    "wrong class for argument: " +
                    argumentName + ", " +
                    "expected class: " +
                    expectedClass + ", " +
                    "wrong value: " +
                    wrongValue + " " +
                    "wrong class: " +
                    wrongValue.getClass() );
        }
    }


    /**
     * Exception
     */
    public static class MissedArgumentException
    extends RuntimeException
    {
        /**
         * Generated by Eclipse.
         */
        private static final long serialVersionUID = 1944167892402238600L;

        /**
         * Constructor.
         *
         * @param message
         */
        public MissedArgumentException(
                final String argumentNames )
        {
            super( argumentNames );
        }
    }

}
