package de.heinerkuecker.coroutine;

import java.util.HashMap;
import java.util.Iterator;
import java.util.Map.Entry;
import java.util.Objects;

public class Variables
implements Iterable<Entry<String, Object>>
{
    private final HashMap<String, Object> innerVars = new HashMap<>();

    private final HashMap<String, Class<?>> types = new HashMap<>();


    public Object get(
            final String variableName )
    {
        // TODO throw exception, when variableName is unknown
        return this.innerVars.get(
                Objects.requireNonNull(
                        variableName ) );
    }

    public void declare(
            final String variableName ,
            final Class<?> type )
    {
        if ( types.containsKey( variableName ) )
        {
            throw new VariableAlreadyDeclaredException(
                    variableName );
        }

        this.types.put(
                Objects.requireNonNull(
                        variableName ) ,
                Objects.requireNonNull(
                        type ) );
    }

    /**
     * Convinience method.
     *
     * @param variableName
     * @param type
     * @param value
     */
    public <T> void declare(
            final String variableName ,
            final Class<T> type ,
            final T value )
    {
        declare(
                variableName ,
                type );

        set(
                Objects.requireNonNull(
                        variableName ) ,
                value );
    }

    public void set(
            final String variableName ,
            final Object value )
    {
        if ( value == null )
        {
            this.innerVars.remove(
                    Objects.requireNonNull(
                            variableName ) );
        }
        else
        {
            if ( types.containsKey( variableName ) )
            {
                if ( ! types.get( variableName ).isInstance( value ) )
                {
                    throw new ClassCastException( value.getClass().toString() );
                }
            }

            this.innerVars.put(
                    Objects.requireNonNull(
                            variableName ) ,
                    value );
        }
    }

    /**
     * @see Object#toString()
     */
    @Override
    public String toString()
    {
        //return "Variables [innerVars=" + this.innerVars + "]";
        return String.valueOf( this.innerVars );
    }

    /**
     * @see java.lang.Iterable#iterator()
     */
    @Override
    public Iterator<Entry<String, Object>> iterator()
    {
        return this.innerVars.entrySet().iterator();
    }

    /**
     * Exception
     */
    public static class VariableAlreadyDeclaredException
    extends RuntimeException
    {

        /**
         * Generated by Eclipse.
         */
        private static final long serialVersionUID = 462065284743881352L;

        /**
         * @param message
         */
        public VariableAlreadyDeclaredException(
                final String variableName )
        {
            super( "variable already declared: " + variableName );
        }

    }

}
