package de.heinerkuecker.coroutine.exprs.exc;

import de.heinerkuecker.coroutine.exprs.GetFunctionArgument;

/**
 * Exception is throwing
 * when a expression
 * {@link GetFunctionArgument}
 * is used outside of an
 * function.
 *
 * @author Heiner K&uuml;cker
 */
public class UseGetFunctionArgumentOutsideOfFunctionException
extends IllegalArgumentException
{
    /**
     * Serial version UID generated by eclipse.
     */
    private static final long serialVersionUID = 7213706475018911385L;

    /**
     * Constructor.
     *
     * @param s
     */
    public UseGetFunctionArgumentOutsideOfFunctionException(
            final String s )
    {
        super(s);
    }

}
