package de.heinerkuecker.coroutine.exprs.exc;

import de.heinerkuecker.coroutine.HasVariableName;

/**
 * Exception
 */
public class WrongExpressionVariableClassException
extends RuntimeException
{
    /**
     * Generated by eclipse.
     */
    private static final long serialVersionUID = 4312073511267054184L;

    /**
     * Constructor.
     */
    public WrongExpressionVariableClassException(
            final HasVariableName wrongExpression ,
            final Class<?> wrongClass ,
            final Class<?> expectedClass )
    {
        super(
                "wrong variable class for expression: " +
                wrongExpression + ",\n" +
                "expected class: " +
                expectedClass + ", " +
                "wrong class: " +
                wrongClass );
    }
}
