package de.heinerkuecker.coroutine.step.simple.exc;

import de.heinerkuecker.coroutine.step.CoroIterStep;

/**
 * Exception
 */
public class StmtVariableIsNullException
extends RuntimeException
{
    /**
     * Generated by Eclipse.
     */
    private static final long serialVersionUID = -31395849829839911L;

    /**
     * Constructor.
     */
    public StmtVariableIsNullException(
            final CoroIterStep<?> wrongStmt ,
            final Class<?> expectedClass )
    {
        super(
                "variable is null for statement: " +
                wrongStmt + ",\n" +
                "expected class: " +
                expectedClass );
    }
}
