package de.heinerkuecker.coroutine.expression.exc;

import de.heinerkuecker.coroutine.expression.GetProcedureArgument;

/**
 * Exception is throwing
 * when a expression
 * {@link GetProcedureArgument}
 * is used outside of an
 * procedure.
 *
 * @author Heiner K&uuml;cker
 */
public class GetProcedureArgumentNotInProcedureException
extends IllegalArgumentException
{
    /**
     * Serial version UID generated by eclipse.
     */
    private static final long serialVersionUID = 7213706475018911385L;

    /**
     * Constructor.
     *
     * @param s
     */
    public GetProcedureArgumentNotInProcedureException(
            final String s )
    {
        super(s);
    }

}
