package de.heinerkuecker.coroutine_iterator.expression;

public class GetProcedureArgumentNotInProcedureException
extends IllegalArgumentException
{
    /**
     * Serial version UID generated by eclipse.
     */
    private static final long serialVersionUID = 7213706475018911385L;

    public GetProcedureArgumentNotInProcedureException(String s) {
        super(s);
        // TODO Auto-generated constructor stub
    }

}
