package de.heinerkuecker.coroutine.expression;

import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import de.heinerkuecker.coroutine.CoroIteratorOrProcedure;
import de.heinerkuecker.coroutine.HasArgumentsAndVariables;
import de.heinerkuecker.coroutine.HasCreationStackTraceElement;
import de.heinerkuecker.coroutine.HasVariableName;
import de.heinerkuecker.coroutine.expression.exc.WrongClassException;

public class GetGlobalVar<T>
extends HasCreationStackTraceElement
implements CoroExpression<T> , HasVariableName
{
    public final String globalVarName;

    /**
     * For type check.
     *
     * Solve unchecked cast.
     */
    public final Class<T> type;

    /**
     * Constructor.
     * @param globalVarName
     */
    public GetGlobalVar(
            final String globalVarName ,
            final Class<T> type )
    {
        super(
                //creationStackOffset
                2 );

        this.globalVarName =
                Objects.requireNonNull(
                        globalVarName );

        this.type =
                Objects.requireNonNull(
                        type );
    }

    @Override
    public T evaluate(
            final HasArgumentsAndVariables/*CoroIteratorOrProcedure<?>*/ parent )
    {
        final Object globalVarValue = parent.globalVars().get( globalVarName );

        if ( globalVarValue != null &&
                ! type.isInstance( globalVarValue ) )
        {
            //throw new ClassCastException(
            //        globalVarValue.getClass().toString() +
            //        ( this.creationStackTraceElement != null
            //            ? " " + this.creationStackTraceElement
            //            : "" ) );
            throw new WrongClassException(
                    //valueExpression
                    this ,
                    //expectedClass
                    type ,
                    //wrongValue
                    globalVarValue );
        }

        return type.cast( globalVarValue );
    }

    @Override
    public List<GetProcedureArgument<?>> getProcedureArgumentGetsNotInProcedure()
    {
        return Collections.emptyList();
    }

    @Override
    public void checkUseVariables(
            HashSet<String> alreadyCheckedProcedureNames ,
            final CoroIteratorOrProcedure<?> parent ,
            final Map<String, Class<?>> globalVariableTypes, final Map<String, Class<?>> localVariableTypes )
    {
        if ( ! globalVariableTypes.containsKey( this.globalVarName ) )
        {
            throw new GlobalVariableNotDeclaredException( this );
        }

        final Class<?> variableType = globalVariableTypes.get( this.globalVarName );

        if ( ! variableType.isAssignableFrom( this.type ) )
        {
            throw new GetLocalVar.WrongVariableClassException(
                    //wrongNamedExpression
                    this ,
                    //wrongClass
                    this.type ,
                    //expectedClass
                    variableType );
        }
    }

    @Override
    public String getVariableName()
    {
        return this.globalVarName;
    }

    @Override
    public void checkUseArguments(
            HashSet<String> alreadyCheckedProcedureNames, final CoroIteratorOrProcedure<?> parent )
    {
        // nothing to do
    }

    @SuppressWarnings("unchecked")
    @Override
    public Class<? extends T>[] type()
    {
        //return type;
        return new Class[] { type };
    }

    /**
     * @see Object#toString()
     */
    @Override
    public String toString()
    {
        return
                this.getClass().getSimpleName() +
                "[" +
                //"globalVarName=" +
                this.globalVarName +
                "]";
    }

    /**
     * Exception
     */
    public static class GlobalVariableNotDeclaredException
    extends RuntimeException
    {
        /**
         * Generated by Eclipse.
         */
        private static final long serialVersionUID = 3720688760091360980L;

        /**
         * Constructor.
         *
         * @param stepOrExpression step or expression with access to not declared global variable
         */
        public <T extends HasCreationStackTraceElement & HasVariableName> GlobalVariableNotDeclaredException(
                final T stepOrExpression )
        {
            super(
                    "global variable not declared: " +
                    stepOrExpression );
        }

    }

}
