package de.heinerkuecker.coroutine.stmt.simple.exc;

import de.heinerkuecker.coroutine.stmt.CoroIterStep;

/**
 * Exception
 */
public class WrongStmtVariableClassException
extends RuntimeException
{
    /**
     * Generated by Eclipse.
     */
    private static final long serialVersionUID = -5512816963256778348L;

    /**
     * Constructor.
     */
    public WrongStmtVariableClassException(
            final CoroIterStep<?> wrongStmt ,
            final Class<?> wrongClass ,
            final Class<?> expectedClass )
    {
        super(
                "wrong variable class for statement: " +
                wrongStmt + ",\n" +
                "expected class: " +
                expectedClass + ", " +
                "wrong class: " +
                wrongClass );
    }
}
