package de.heinerkuecker.coroutine.stmt.flow.exc;

import de.heinerkuecker.coroutine.stmt.flow.Break;
import de.heinerkuecker.coroutine.stmt.flow.Continue;

/**
 * Exception is throwing
 * when a {@link Break}
 * or {@link Continue}
 * is used outside of an
 * loop or the label of
 * the {@link Break}
 * or {@link Continue}
 * is unknown.
 *
 * @author Heiner K&uuml;cker
 */
public class UnresolvedBreakOrContinueException
extends IllegalArgumentException
{
    /**
     * Serial version UID generated by eclipse.
     */
    private static final long serialVersionUID = 7213706475018911385L;

    /**
     * Constructor.
     *
     * @param s
     */
    public UnresolvedBreakOrContinueException(
            final String s )
    {
        super(s);
    }

}
